<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CompetitionSeeder extends Seeder
{
    public function run(): void
    {
        $now = now();
        $location = 'SMP Muhammadiyah Unggulan Ashidiq';
        $contact = '0812-7757-0669 (Ust. Nur Wahyudi)';
        $prize1 = 'Rp 500.000+Trophy+Sertifikat';
        $prize2 = 'Rp 300.000+Trophy+Sertifikat';
        $prize3 = 'Rp 200.000+Trophy+Sertifikat';

        $competitions = [
            [
                'slug' => 'olimpiade-ipas',
                'name' => 'Olimpiade IPAS',
                'category' => 'Akademik',
                'level' => 'SD',
                'quota' => 100,
                'status' => 'OPEN',
                'team_size' => 1,
                'prize_1' => $prize1,
                'prize_2' => $prize2,
                'prize_3' => $prize3,
                'location' => $location,
                'contact_person' => $contact,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'olimpiade-matematika',
                'name' => 'Olimpiade Matematika',
                'category' => 'Akademik',
                'level' => 'SD',
                'quota' => 100,
                'status' => 'OPEN',
                'team_size' => 1,
                'prize_1' => $prize1,
                'prize_2' => $prize2,
                'prize_3' => $prize3,
                'location' => $location,
                'contact_person' => $contact,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'cerdas-cermat-agama',
                'name' => 'Cerdas Cermat Agama',
                'category' => 'Religi',
                'level' => 'SD',
                'quota' => 100,
                'status' => 'OPEN',
                'team_size' => 3,
                'prize_1' => $prize1,
                'prize_2' => $prize2,
                'prize_3' => $prize3,
                'location' => $location,
                'contact_person' => $contact,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'mhq',
                'name' => 'MHQ',
                'category' => 'Religi',
                'level' => 'SD',
                'quota' => 100,
                'status' => 'OPEN',
                'team_size' => 1,
                'prize_1' => $prize1,
                'prize_2' => $prize2,
                'prize_3' => $prize3,
                'location' => $location,
                'contact_person' => $contact,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'mtq',
                'name' => 'MTQ',
                'category' => 'Religi',
                'level' => 'SD',
                'quota' => 100,
                'status' => 'OPEN',
                'team_size' => 1,
                'prize_1' => $prize1,
                'prize_2' => $prize2,
                'prize_3' => $prize3,
                'location' => $location,
                'contact_person' => $contact,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'pildacil',
                'name' => 'Pildacil',
                'category' => 'Seni',
                'level' => 'SD',
                'quota' => 100,
                'status' => 'OPEN',
                'team_size' => 1,
                'prize_1' => $prize1,
                'prize_2' => $prize2,
                'prize_3' => $prize3,
                'location' => $location,
                'contact_person' => $contact,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'story-telling',
                'name' => 'Story Telling',
                'category' => 'Bahasa',
                'level' => 'SD',
                'quota' => 100,
                'status' => 'OPEN',
                'team_size' => 1,
                'prize_1' => $prize1,
                'prize_2' => $prize2,
                'prize_3' => $prize3,
                'location' => $location,
                'contact_person' => $contact,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'maca-cerak',
                'name' => 'Maca Cerak',
                'category' => 'Bahasa',
                'level' => 'SD',
                'quota' => 100,
                'status' => 'OPEN',
                'team_size' => 1,
                'prize_1' => $prize1,
                'prize_2' => $prize2,
                'prize_3' => $prize3,
                'location' => $location,
                'contact_person' => $contact,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'membaca-puisi',
                'name' => 'Membaca Puisi',
                'category' => 'Seni',
                'level' => 'SD',
                'quota' => 100,
                'status' => 'OPEN',
                'team_size' => 1,
                'prize_1' => $prize1,
                'prize_2' => $prize2,
                'prize_3' => $prize3,
                'location' => $location,
                'contact_person' => $contact,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'menggambar',
                'name' => 'Menggambar',
                'category' => 'Seni',
                'level' => 'SD',
                'quota' => 100,
                'status' => 'OPEN',
                'team_size' => 1,
                'prize_1' => $prize1,
                'prize_2' => $prize2,
                'prize_3' => $prize3,
                'location' => $location,
                'contact_person' => $contact,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'fotografi',
                'name' => 'Fotografi',
                'category' => 'Seni',
                'level' => 'SD',
                'quota' => 100,
                'status' => 'OPEN',
                'team_size' => 1,
                'prize_1' => $prize1,
                'prize_2' => $prize2,
                'prize_3' => $prize3,
                'location' => $location,
                'contact_person' => $contact,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'video-pendek',
                'name' => 'Video Pendek',
                'category' => 'Seni',
                'level' => 'SD',
                'quota' => 100,
                'status' => 'OPEN',
                'team_size' => 3,
                'prize_1' => $prize1,
                'prize_2' => $prize2,
                'prize_3' => $prize3,
                'location' => $location,
                'contact_person' => $contact,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        DB::table('competitions')->insert($competitions);
    }
}
